title = "WarmUp 2026"

[[weights]]
name = "Ostatní"
weight = 1

[[weights]]
name = "VUT"
weight = 2

[[weights]]
name = "FEKT"
weight = 3

[[options]]
name = "Unhinged V"

[[options]]
name = "Aldente"

[[options]]
name = "Preceptor"

[[options]]
name = "Tight Trail"